const ScriptToCode = {
    "adlam": "Adlm",
    "afaka": "Afak",
    "caucasian albanian": "Aghb",
    "ahom": "Ahom",
    "arabic (nastaliq variant)": "Aran",
    "imperial aramaic": "Armi",
    "armenian": "Armn",
    "avestan": "Avst",
    "balinese": "Bali",
    "bamum": "Bamu",
    "bassa vah": "Bass",
    "batak": "Batk",
    "bengali": "Beng",
    "bhaiksuki": "Bhks",
    "blissymbols": "Blis",
    "bopomofo": "Bopo",
    "brahmi": "Brah",
    "braille": "Brai",
    "buginese": "Bugi",
    "buhid": "Buhd",
    "chakma": "Cakm",
    "unified canadian aboriginal syllabics": "Cans",
    "carian": "Cari",
    "cham": "Cham",
    "cherokee": "Cher",
    "chisoi": "Chis",
    "chorasmian": "Chrs",
    "cirth": "Cirt",
    "coptic": "Copt",
    "cypro-minoan": "Cpmn",
    "cypriot syllabary": "Cprt",
    "cyrillic": "Cyrl",
    "cyrillic (old church slavonic variant)": "Cyrs",
    "devanagari": "Deva",
    "dives akuru": "Diak",
    "dogra": "Dogr",
    "deseret": "Dsrt",
    "duployan shorthand": "Dupl",
    "egyptian demotic": "Egyd",
    "egyptian hieratic": "Egyh",
    "egyptian hieroglyphs": "Egyp",
    "elbasan": "Elba",
    "elymaic": "Elym",
    "ethiopic": "Ethi",
    "garay": "Gara",
    "khutsuri (asomtavruli and nuskhuri)": "Geok",
    "georgian (mkhedruli and mtavruli)": "Geor",
    "glagolitic": "Glag",
    "gunjala gondi": "Gong",
    "masaram gondi": "Gonm",
    "gothic": "Goth",
    "grantha": "Gran",
    "greek": "Grek",
    "gujarati": "Gujr",
    "gurung khema": "Gukh",
    "gurmukhi": "Guru",
    "han with bopomofo": "Hanb",
    "hangul": "Hang",
    "han": "Hani",
    "hanunoo": "Hano",
    "han (simplified variant)": "Hans",
    "han (traditional variant)": "Hant",
    "hatran": "Hatr",
    "hebrew": "Hebr",
    "hiragana": "Hira",
    "anatolian hieroglyphs": "Hluw",
    "pahawh hmong": "Hmng",
    "nyiakeng puachue hmong": "Hmnp",
    "japanese syllabaries": "Hrkt",
    "old hungarian": "Hung",
    "indus": "Inds",
    "old italic": "Ital",
    "jamo": "Jamo",
    "javanese": "Java",
    "japanese": "Jpan",
    "jurchen": "Jurc",
    "kayah li": "Kali",
    "katakana": "Kana",
    "kawi": "Kawi",
    "kharoshthi": "Khar",
    "khmer": "Khmr",
    "khojki": "Khoj",
    "khitan large script": "Kitl",
    "khitan small script": "Kits",
    "kannada": "Knda",
    "korean": "Kore",
    "kpelle": "Kpel",
    "kirat rai": "Krai",
    "kaithi": "Kthi",
    "tai tham": "Lana",
    "lao": "Laoo",
    "latin (fraktur variant)": "Latf",
    "latin (gaelic variant)": "Latg",
    "latin": "Latn",
    "leke": "Leke",
    "lepcha": "Lepc",
    "limbu": "Limb",
    "linear a": "Lina",
    "linear b": "Linb",
    "lisu": "Lisu",
    "loma": "Loma",
    "lycian": "Lyci",
    "lydian": "Lydi",
    "mahajani": "Mahj",
    "makasar": "Maka",
    "mandaic": "Mand",
    "manichaean": "Mani",
    "marchen": "Marc",
    "mayan hieroglyphs": "Maya",
    "medefaidrin": "Medf",
    "mende kikakui": "Mend",
    "meroitic cursive": "Merc",
    "meroitic hieroglyphs": "Mero",
    "malayalam": "Mlym",
    "modi": "Modi",
    "mongolian": "Mong",
    "moon": "Moon",
    "mro": "Mroo",
    "meitei mayek": "Mtei",
    "multani": "Mult",
    "myanmar": "Mymr",
    "nag mundari": "Nagm",
    "nandinagari": "Nand",
    "old north arabian": "Narb",
    "nabataean": "Nbat",
    "newa": "Newa",
    "naxi dongba": "Nkdb",
    "naxi geba": "Nkgb",
    "n’ko": "Nkoo",
    "nüshu": "Nshu",
    "ogham": "Ogam",
    "ol chiki": "Olck",
    "ol onal": "Onao",
    "old turkic": "Orkh",
    "oriya": "Orya",
    "osage": "Osge",
    "osmanya": "Osma",
    "old uyghur": "Ougr",
    "palmyrene": "Palm",
    "pau cin hau": "Pauc",
    "proto-cuneiform": "Pcun",
    "proto-elamite": "Pelm",
    "old permic": "Perm",
    "phags-pa": "Phag",
    "inscriptional pahlavi": "Phli",
    "psalter pahlavi": "Phlp",
    "book pahlavi": "Phlv",
    "phoenician": "Phnx",
    "klingon": "Piqd",
    "miao": "Plrd",
    "inscriptional parthian": "Prti",
    "proto-sinaitic": "Psin",
    "ranjana": "Ranj",
    "rejang": "Rjng",
    "hanifi rohingya": "Rohg",
    "rongorongo": "Roro",
    "runic": "Runr",
    "samaritan": "Samr",
    "sarati": "Sara",
    "old south arabian": "Sarb",
    "saurashtra": "Saur",
    "signwriting": "Sgnw",
    "shavian": "Shaw",
    "sharada": "Shrd",
    "shuishu": "Shui",
    "siddham": "Sidd",
    "sidetic": "Sidt",
    "khudawadi": "Sind",
    "sinhala": "Sinh",
    "sogdian": "Sogd",
    "old sogdian": "Sogo",
    "sora sompeng": "Sora",
    "soyombo": "Soyo",
    "sundanese": "Sund",
    "sunuwar": "Sunu",
    "syloti nagri": "Sylo",
    "syriac": "Syrc",
    "syriac (estrangelo variant)": "Syre",
    "syriac (western variant)": "Syrj",
    "syriac (eastern variant)": "Syrn",
    "tagbanwa": "Tagb",
    "takri": "Takr",
    "tai le": "Tale",
    "new tai lue": "Talu",
    "tamil": "Taml",
    "tangut": "Tang",
    "tai viet": "Tavt",
    "tai yo": "Tayo",
    "telugu": "Telu",
    "tengwar": "Teng",
    "tifinagh": "Tfng",
    "tagalog": "Tglg",
    "thaana": "Thaa",
    "thai": "Thai",
    "tibetan": "Tibt",
    "tirhuta": "Tirh",
    "tangsa": "Tnsa",
    "todri": "Todr",
    "tolong siki": "Tols",
    "toto": "Toto",
    "tulu-tigalari": "Tutg",
    "ugaritic": "Ugar",
    "vai": "Vaii",
    "visible speech": "Visp",
    "vithkuqi": "Vith",
    "warang citi": "Wara",
    "wancho": "Wcho",
    "woleai": "Wole",
    "old persian": "Xpeo",
    "sumero-akkadian cuneiform": "Xsux",
    "yezidi": "Yezi",
    "yi": "Yiii",
    "zanabazar square": "Zanb"
}
module.exports = ScriptToCode;
