const Predefined = {
    "en-US": "English",
    "en-GB": "British English",
    "en-CA": "Canadian English",
    "en-AU": "Australian English",
    "es-ES": "Spanish",
    "es-MX": "Mexican Spanish",
    "es-AR": "Argentinian Spanish",
    "es-CO": "Colombian Spanish",
    "fr-FR": "French",
    "fr-CA": "Canadian French",
    "fr-BE": "Belgian French",
    "fr-CH": "Swiss French",
    "zh-CN": "Mandarin Chinese",
    "zh-TW": "Traditional Chinese",
    "zh-HK": "Hong Kong Chinese",
    "pt-PT": "Portuguese",
    "pt-BR": "Brazilian Portuguese",
    "de-DE": "German",
    "de-AT": "Austrian German",
    "de-CH": "Swiss German",
    "ar-SA": "Saudi Arabic",
    "ar-EG": "Egyptian Arabic",
    "ar-AE": "Emirati Arabic",
    "ar-MA": "Moroccan Arabic",
    "nl-BE": "Belgian Dutch",
    "it-CH": "Swiss Italian"
};
module.exports = Predefined;
